### ISSUE TITLE
your latest update broke heavy rainfall in act 1, at least in my mod..

### ISSUE THREAD

**Issue by skylight102** [Jarcho/d2-rs#2]
The rain looks like long crazy spazzy lines (im using 1280 x 720 resolution on 1.13c).

**Comment by Jarcho** [comment]
This needs more information. Log file? Image/video of "long crazy spazzy lines"? What mods are used?

**Comment by skylight102** [comment]
Pd2 but an old season, all I know is it is fine in the version just before this one.

Will provide log later

On 30 Jan 2024, at 18:22, Jason Newcomb ***@***.***> wrote:

﻿

This needs more information. Log file? Image/video of "long crazy spazzy lines"? What mods are used?

**Comment by weili0677** [comment]
I happened once.It's not easy to repeat

**Comment by skylight102** [comment]
![image](https://github.com/Jarcho/d2-rs/assets/66263871/f0df6250-f6e4-4167-9312-8c2f541a1f81)

**Comment by skylight102** [comment]
![image](https://github.com/Jarcho/d2-rs/assets/66263871/ad08b45d-d82f-403e-b20d-5042fd7b7157)

**Comment by weili0677** [comment]
> ![image](https://private-user-images.githubusercontent.com/66263871/301464200-ad08b45d-d82f-403e-b20d-5042fd7b7157.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MDAxOTIsIm5iZiI6MTcwNjc5OTg5MiwicGF0aCI6Ii82NjI2Mzg3MS8zMDE0NjQyMDAtYWQwOGI0NWQtZDgyZi00MDNlLWIyMGQtNTA0MmZkN2I3MTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDE1MDQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0M2Y3OWExMjFmMmJmOGI1NDAxMjI0Nzc5OGQ0NTUzMjlmZThhMTE0YzhmZDg1MDYwYjVmZThlYjJkNDMxNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B1ShKqn0M_xht0A5b4Sj1rS8axRVOIdZsEi0DWRgOWk)

me too

**Comment by Jarcho** [comment]
I think I know what caused that. Can you test [this version](https://github.com/Jarcho/d2-rs/files/14142028/d2fps-rainfix.zip) and let me know?

**Comment by skylight102** [comment]
Have been unable to replicate after 2 hours of play, but I'll let you know over the next day or so to make sure. Thank you :)

**Comment by skylight102** [comment]
Still unable to repro, seems to have fixed it.
