### ISSUE TITLE
Add Cursor to Motion smoothing

### ISSUE THREAD

**Issue by qwertyue** [Jarcho/d2-rs#6]

**Comment by Jarcho** [comment]
The cursor movement is already handled when increasing the frame rate.

**Comment by qwertyue** [comment]
> The cursor movement is already handled when increasing the frame rate.

Looking forward to the new release.

**Comment by Jarcho** [comment]
It's already in the current version. The game already updates the mouse cursor immediately so the only thing that needs to happen is increasing the frame rate.

**Comment by qwertyue** [comment]
> It's already in the current version. The game already updates the mouse cursor immediately so the only thing that needs to happen is increasing the frame rate.



> It's already in the current version. The game already updates the mouse cursor immediately so the only thing that needs to happen is increasing the frame rate.

get it
